config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  root :to =>"homes#top"
  get "about", to: "homes#about", as: "about"

  scope module: :public do
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show]
  end

  namespace :admin do
    root :to =>'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, presence: true
  validates :name,        presence: true
  validates :postal_code, presence: true
  validates :address,     presence: true

  validates :postal_code, format: { with: /\A\d{7}\z/, message: "は7桁の数字で入力してください" }
  validates :address, length: { minimum: 2, message: "は2文字以上で入力してください" }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { greater_than: 0 }

  def subtotal
    item.price_in_tax * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: :true
  validates :first_name, presence: :true
  validates :last_name_kana, presence: :true
  validates :first_name_kana, presence: :true
  validates :postal_code, presence: :true
  validates :telephone_number, presence: :true
  validates :address, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


#画像のサイズを変更するメソッド
  def get_image
    if image.attached?
        image.variant(resize_to_fill: [width = 300, height = 300]).processed
    end
  end

#税込金額を算出するメソッド
  def price_in_tax
    (price * 1.1).floor  #(税抜価格✕税率).小数点以下切り捨てメソッド
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  before_create :generate_order_id
  has_many :items, through: :order_details
  has_many :order_details, dependent: :destroy
 

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true


  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4 }

  after_update :update_making_status, if: :saved_change_to_status?
  
  private

  def update_making_status
    if status == "paid_up"
      order_details.where(making_status: OrderDetail.making_statuses[:cannot_start])
                   .update_all(making_status: OrderDetail.making_statuses[:waiting_for_make])
    end
  end

  def generate_order_id
    self.order_id = Time.current.strftime('%Y%m%d%H%M%S') + rand(1000..9999).to_s
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.price_in_tax * amount
  end

  enum making_status: {
    cannot_start: 0,    
    waiting_for_make: 1, 
    in_production: 2,    
    complete: 3          
  }

  after_update :update_order_status, if: :saved_change_to_making_status?

  private

  def update_order_status
    if in_production?
      order.update(status: :production) unless order.production?
      return
    end
    
    if order.order_details.all?(&:complete?)
      order.update(status: :preparing) unless order.preparing?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.includes(:customer).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new(is_active: true)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item =Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end



  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @new_items = Item.order(created_at: :desc).limit(4)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/items/_form.html.erb
<div class="mb-3 row ">
  <%= f.label :image, "商品画像", class: "col-5 col-form-label" %>
  <div class="col-6">
    <%= f.file_field :image, accept: "image/*" %>
  </div>
</div>

<div class="mb-3 row">
  <%= f.label :name, "商品名", class: "col-5 col-form-label" %>
  <div class="col-6">
    <%= f.text_field :name, class: "form-control" %>
  </div>
</div>

<div class="mb-3 row">
  <%= f.label :introduction, "商品説明", class: "col-5 col-form-label" %>
  <div class="col-6">
    <%= f.text_area :introduction,  rows: 5, class: "form-control" %>
  </div>
</div>

<div class="mb-3 row">
  <%= f.label :genre_id, "ジャンル", class: "col-5 col-form-label" %>
  <div class="col-6">
    <%= f.collection_select :genre_id, Genre.all, :id, :name,{ prompt: '--選択してください--' }, { class: "form-control" } %>
  </div>
</div>

<div class="mb-3 row">
  <%= f.label :price, "税抜価格", class: "col-5 col-form-label" %>
    <div class= "col-6 d-flex align-items-center">
    <%= f.text_field :price, class: "form-control" %>
    <span class="ms-5">円</span>
    </div>
</div>


<div class="mb-3 row d-flex align-items-baseline">
  <%= f.label :is_active, "販売ステータス", class: "col-5 col-form-label" %>
  <div class="col-6">
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, "販売中", value:true %>

    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active, "販売停止中", value:false %>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class = "container my-4">
  <div class = "row px-2">
    <div class= "text-center thead-color px-3">
      <h2>商品編集</h2>
    </div>
  </div>
  
    <% if @item.errors.any? %>
      <div class = "alert alert-danger w-50">
        <%= @item.errors.count %>件のエラーが発生しました。
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
</div>

<div class = "container w-100 mt-4 d-flex flex-column align-items-center justify-content-around ">
  <%= form_with model: [:admin,@item], local: true, class: "w-75" do |f| %>
    <%= render 'form', item: @item, f:f %>
    <div class="text-center">
      <%= f.submit "編集を保存", class: " mb-2 btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
  <div class = "row align-item-baseline  d-flex d-row justify-content-between my-3 ml-5">
    <div class = "bg-light ml-5">
      <h2 class = "px-3">商品一覧</h2>
    </div>
    <div class = "col-2">
      <%= link_to "新規登録", new_admin_item_path, class: "btn btn-primary btn-lg rounded-circle " %>
    </div>
  </div>

<div class="d-flex justify-content-center">
  <table class = "table table-hover w-75" >
    <thead class="thead-color">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th></th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody class="tbody-color">
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td>
          <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
          <% end %>
        </td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td></td>
        <td>
          <div class ="<%= item.is_active ? 'text-success' : 'text-secondary' %>">
            <%= item.is_active ? "販売中" : "販売停止中" %>
          </div>
        </td>
      </tr>
      <% end %>
      </tbody>
  </table>
</div>

<div class = "d-flex justify-content-around">
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class = "container my-4">
  <div class = "row px-2">
    <div  class= "text-center thead-color px-3">
      <h2>商品新規登録</h2>
    </div>
  </div>
  
    <% if @item.errors.any? %>
      <div class = "alert alert-danger w-50">
        <%= @item.errors.count %>件のエラーが発生しました。
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
</div>

  <div class = "container w-100 mt-4 d-flex flex-column align-items-center justify-content-around ">
    <%= form_with model: [:admin,@item], local: true, class: "w-75" do |f| %>
      <%= render 'form', item: @item, f: f %>
      <div class="text-center">
      <%= f.submit "新規登録", class: "px-4 mb-2 btn btn-success" %>
      </div>
    <% end %>
  </div>

app/views/admin/items/show.html.erb
<div class = "container my-4">
  <div class = "row d-flex justify-content-between">
    <div class = "text-center">
      <h2 class = "thead-color px-3">商品詳細</h2>
    </div>
  </div>

  <div class = "row mt-5">
    <div class = "col-4 text-center">
      <%= image_tag @item.get_image %>
    </div>
    <dl class="row col-8 px-5">
      <dt class="col-3">商品名</dt>
      <dd class="col-9"><%= @item.name %></dd>

      <dt class="col-3">商品説明</dt>
      <dd class="col-9"><%= @item.introduction %></dd>

      <dt class="col-3">ジャンル</dt>
      <dd class="col-9"><%= @item.genre.name %></dd>

      <dt class="col-3">税込価格（税抜価格）</dt>
      <dd class="col-9">
        <%= number_to_currency(@item.price_in_tax, unit: "円", precision: 0) %>
          （<%= number_to_currency(@item.price, unit: "円", precision: 0) %>）
      </dd>

      <dt class="col-3">販売ステータス</dt>
      <dd class="col-9">
        <% if @item.is_active %>
          <div class="text-success">販売中</div>
        <% else %>
          <div class="text-secondary">販売停止中</div>
        <% end %>
      </dd>
    </dl>
  </div>
</div>
<div class="text-center">
<%= link_to "編集する", edit_admin_item_path(@item), class: "mb-2 btn btn-success" %>
</div>