config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  root :to =>"homes#top"
  get "about", to: "homes#about", as: "about"

  scope module: :public do
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show]
  end

  namespace :admin do
    root :to =>'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, presence: true
  validates :name,        presence: true
  validates :postal_code, presence: true
  validates :address,     presence: true

  validates :postal_code, format: { with: /\A\d{7}\z/, message: "は7桁の数字で入力してください" }
  validates :address, length: { minimum: 2, message: "は2文字以上で入力してください" }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { greater_than: 0 }

  def subtotal
    item.price_in_tax * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: :true
  validates :first_name, presence: :true
  validates :last_name_kana, presence: :true
  validates :first_name_kana, presence: :true
  validates :postal_code, presence: :true
  validates :telephone_number, presence: :true
  validates :address, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


#画像のサイズを変更するメソッド
  def get_image
    if image.attached?
        image.variant(resize_to_fill: [width = 300, height = 300]).processed
    end
  end

#税込金額を算出するメソッド
  def price_in_tax
    (price * 1.1).floor  #(税抜価格✕税率).小数点以下切り捨てメソッド
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  before_create :generate_order_id
  has_many :items, through: :order_details
  has_many :order_details, dependent: :destroy
 

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true


  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4 }

  after_update :update_making_status, if: :saved_change_to_status?
  
  private

  def update_making_status
    if status == "paid_up"
      order_details.where(making_status: OrderDetail.making_statuses[:cannot_start])
                   .update_all(making_status: OrderDetail.making_statuses[:waiting_for_make])
    end
  end

  def generate_order_id
    self.order_id = Time.current.strftime('%Y%m%d%H%M%S') + rand(1000..9999).to_s
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.price_in_tax * amount
  end

  enum making_status: {
    cannot_start: 0,    
    waiting_for_make: 1, 
    in_production: 2,    
    complete: 3          
  }

  after_update :update_order_status, if: :saved_change_to_making_status?

  private

  def update_order_status
    if in_production?
      order.update(status: :production) unless order.production?
      return
    end
    
    if order.order_details.all?(&:complete?)
      order.update(status: :preparing) unless order.preparing?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.includes(:customer).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new(is_active: true)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item =Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end



  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @new_items = Item.order(created_at: :desc).limit(4)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class='container W-100 my-3'>
  <div class='row my-4 w-75'>
    <div class="col-12">
      <h4 class="table-light thead-color px-3 text-start d-inline-block">
        <%= "#{@customer.last_name}#{@customer.first_name}" %>さんの会員情報編
      </h4>

        <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>

          <div class="form-row my-3">
            <label class="col-md-2 col-form-label">
              会員ID
            </label>
            <div class="col-md-5">
              <p class="form-control-plaintext">
                <%= @customer.id %>
              </p>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-form-label col-md-2">
              氏名
            </div>
            <div class="col-md-3">
              <%= f.text_field :last_name, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-form-label col-md-2">
              フリガナ
            </div>
            <div class="col-md-3">
              <%= f.text_field :last_name_kana, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= f.text_field :first_name_kana, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-form-label col-md-2">
              郵便番号
            </div>
            <div class="col-md-3">
              <%= f.number_field :postal_code, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-form-label col-md-2">
              住所
            </div>
            <div class="col-md-10">
              <%= f.text_field :address, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-form-label col-md-2">
              電話番号
            </div>
            <div class="col-md-3">
              <%= f.number_field :telephone_number, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-form-label col-md-2">
              メールアドレス
            </div>
            <div class="col-md-3">
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-3">
            <label class="col-md-2 col-form-label">
              会員ステータス
            </label>
            <div class="col-md-1">
              <p class="form-control-plaintext">
                <%= f.radio_button :is_active, true, class: 'ml-1' %>
                <%= f.label :is_active_true, '有効' %>
              </p>
            </div>
            <div class="col-md-1">
              <p class="form-control-plaintext">
                <%= f.radio_button :is_active, false, class: 'ml-1' %>
                <%= f.label :is_active_false, '無効' %>
              </p>
            </div>
          </div>

          <div class="form-row mb-3">
            <div class="col-md-5">
              <%= f.submit "変更を保存", class: "btn btn-success" %>
            </div>
          </div>

        <% end %>
    </div>
  </div>
</div>
      

app/views/admin/customers/index.html.erb
<div class='container W-100 my-3'>
  <div class='row my-4 w-75'>
    <div class="col-12">
      <h2 class="table-light bg-light px-3 text-start d-inline-block">会員一覧</h2>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
  <table class='table table-hover table-inverse my-2 w-75'>
    <thead class="thead-color">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody class="tbody-color">
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to "#{customer.last_name} #{customer.first_name}", admin_customer_path(customer) %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-secondary">無効</div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class='container W-100 my-3'>
  <div class='row my-4 w-75'>
    <div class="col-12">
      <h4 class="table-light thead-color px-3 mb-3 text-start d-inline-block">
        <%= "#{@customer.last_name}#{@customer.first_name}" %>さんの会員詳細
      </h4>
      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          会員ID
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= @customer.id %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          氏名
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= "#{@customer.last_name}#{@customer.first_name}" %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          フリガナ
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= "#{@customer.last_name_kana}#{@customer.first_name_kana}" %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          郵便番号
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= @customer.postal_code %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          住所
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= @customer.address %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          電話番号
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= @customer.telephone_number %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          メールアドレス
        </div>
        <div class="col-md-5">
          <p class="form-control-plaintext">
            <%= @customer.email %>
          </p>
        </div>
      </div>

      <div class="form-row mb-2">
        <div class="col-form-label col-md-2">
          会員ステータス
        </div>
        <div class="col-md-5">
          <% if @customer.is_active %>
            <div class="form-control-plaintext text-success">有効</div>
          <% else %>
            <div class="form-control-plaintext text-secondary">無効</div>
          <% end %>
        </div>
      </div>

      <div class="form-row mb-3">
        <div class="col-md-3">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
        </div>
        <div class="col-md-3">
          <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>