config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  root :to =>"homes#top"
  get "about", to: "homes#about", as: "about"

  scope module: :public do
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show]
  end

  namespace :admin do
    root :to =>'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, presence: true
  validates :name,        presence: true
  validates :postal_code, presence: true
  validates :address,     presence: true

  validates :postal_code, format: { with: /\A\d{7}\z/, message: "は7桁の数字で入力してください" }
  validates :address, length: { minimum: 2, message: "は2文字以上で入力してください" }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { greater_than: 0 }

  def subtotal
    item.price_in_tax * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: :true
  validates :first_name, presence: :true
  validates :last_name_kana, presence: :true
  validates :first_name_kana, presence: :true
  validates :postal_code, presence: :true
  validates :telephone_number, presence: :true
  validates :address, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


#画像のサイズを変更するメソッド
  def get_image
    if image.attached?
        image.variant(resize_to_fill: [width = 300, height = 300]).processed
    end
  end

#税込金額を算出するメソッド
  def price_in_tax
    (price * 1.1).floor  #(税抜価格✕税率).小数点以下切り捨てメソッド
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  before_create :generate_order_id
  has_many :items, through: :order_details
  has_many :order_details, dependent: :destroy
 

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true


  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4 }

  after_update :update_making_status, if: :saved_change_to_status?
  
  private

  def update_making_status
    if status == "paid_up"
      order_details.where(making_status: OrderDetail.making_statuses[:cannot_start])
                   .update_all(making_status: OrderDetail.making_statuses[:waiting_for_make])
    end
  end

  def generate_order_id
    self.order_id = Time.current.strftime('%Y%m%d%H%M%S') + rand(1000..9999).to_s
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.price_in_tax * amount
  end

  enum making_status: {
    cannot_start: 0,    
    waiting_for_make: 1, 
    in_production: 2,    
    complete: 3          
  }

  after_update :update_order_status, if: :saved_change_to_making_status?

  private

  def update_order_status
    if in_production?
      order.update(status: :production) unless order.production?
      return
    end
    
    if order.order_details.all?(&:complete?)
      order.update(status: :preparing) unless order.preparing?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.includes(:customer).page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new(is_active: true)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item =Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end



  private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :genre_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @new_items = Item.order(created_at: :desc).limit(4)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class = " row px-5 ml-5 my-4">
  <div  class= "text-center thead-color px-3">
    <h2>ジャンル編集</h2>
  </div>
</div>

  <% if @genre.errors.any? %>
    <div class = "row ml-5 w-25 alert alert-danger d-flex flex-column">
      <%= @genre.errors.count %>件のエラーが発生しました。
        <ul>
          <% @genre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

<%= form_with model: [:admin,@genre], local: true, class: "ml-3 w-50" do |f| %>
  <div class= "mb-3 row d-flex flex-row align-items-baseline">
    <%= f.label :name, "ジャンル名", class: "px-3" %>
    <%= f.text_field :name, class: "form-control w-25 mr-2" %>
    <%= f.submit "編集を保存", class: "btn btn-success px-3" %>
  </div>
<% end %>

app/views/admin/genres/index.html.erb
<div class = "row px-5 ml-5 my-4">
  <div class = "text-center px-3">
    <h2>ジャンル一覧・追加</h2>
  </div>
</div>

  <% if @genre.errors.any? %>
    <div class = "row ml-5 w-25 alert alert-danger d-flex flex-column ">
      <%= @genre.errors.count %>件のエラーが発生しました。
        <ul>
          <% @genre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

<%= form_with model: [:admin,@genre], local:true, class: "ml-3 w-50" do |f| %>
  <div class= "mb-3 row d-flex flex-row align-items-baseline">
    <%= f.label :name, "ジャンル名", class: "px-3" %>
    <%= f.text_field :name, class: "form-control w-25 mr-2" %>
  <%= f.submit "新規登録", class: "btn btn-success px-4" %>
  </div>
<% end %>


<table class="table table-sm ml-3 col-4">
  <thead class="thead-color">
    <tr>
      <th>ジャンル</th>
      <th></th>
    </tr>
  </thead>

  <tbody class="tbody-color">
  <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/homes/top.html.erb
<div class="container w-100 my-4 d-flex flex-row justify-content-center">
  <div class="row align-items-baseline d-flex justify-content-between w-75 my-3">
    <h2 class="bg-light px-3">注文履歴一覧</h2>
  </div>
</div>

<div class="d-flex justify-content-center">
  <table class="table table-hover w-75">    
    <thead class="thead-color">
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <tbody class="tbody-color">
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to order.created_at.strftime("%Y-%m-%d %H:%M"), admin_order_path(order) %>
          </td>
          <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
          <td><%= order.order_details.sum(:amount) %></td>
          <td><%= order.status_i18n %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div> 

<div class="d-flex justify-content-center my-3">
  <div class="w-75">
    <%= paginate @orders %>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row my-4'>
    <h1 class="m-auto fs">About</h1>
  </div>
  <div class='row '>
    <p class="mx-auto font-weight text-center">ながのCAKEは全国発送可能なケーキ屋さんです。<br>
    お子様からお年寄りの方までお召し上がりいただけるよう、<br>
    様々なバリエーションをご用意しております。<br>
    また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
    ぜひご注文ください。</p>
  </div>
  <div class="row mb-5">
    <%= image_tag "パティシエ.jpg", class: "m-auto img-fluid", style: "width: 60%;" %>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container my-4">
  <div class="row">
  <%= render 'public/shared/genre_sidebar' %>

    <div class="col-9">
      <div class="position-relative d-inline-block">
      <%= image_tag "ケーキ屋内観.jpg", class: "img-fluid", style: "width: 80%;" %>
        <div class="position-absolute text-dark py-3 border border-dark"
          style="top: 50%; left: 40%; transform: translate(-50%, -50%); width: 400px;
          background-color: rgba(255,255,255,0.7);">
          <p class=" text-center font-weight">ようこそ、ながのCAKEへ!<br>
          このサイトは、ケーキ販売のECサイトになります。<br>
          会員でない方も商品の閲覧はできますが、<br>
          購入には会員登録が必要になります。</p>
        </div>
      </div>

      <h3 class="fw-bold my-3">新着商品</h3>
      <div class="row">
        <% @new_items.first(4).each do |item| %>
          <div class="col-3 text-center mb-4">
            <div class="border p-2">
              <%= link_to item_path(item) do %>
                <%= image_tag item.image.attached? ? url_for(item.image) : "no_image.jpg",
                              class: "img-fluid mb-2" %>
              <% end %>
              <p><%= item.name %></p>
              <p>¥<%= item.price.to_s(:delimited) %></p>
            </div>
          </div>
        <% end %>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to "全ての商品を見る >", items_path, class: "text-primary" %>
      </div>
    </div>
  </div>
</div>