config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  root :to =>"homes#top"
  get "about", to: "homes#about", as: "about"

  scope module: :public do
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'

    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'

    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :genres, only: [:show]
  end

  namespace :admin do
    root :to =>'homes#top'

    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, presence: true
  validates :name,        presence: true
  validates :postal_code, presence: true
  validates :address,     presence: true

  validates :postal_code, format: { with: /\A\d{7}\z/, message: "は7桁の数字で入力してください" }
  validates :address, length: { minimum: 2, message: "は2文字以上で入力してください" }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: { greater_than: 0 }

  def subtotal
    item.price_in_tax * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  validates :last_name, presence: :true
  validates :first_name, presence: :true
  validates :last_name_kana, presence: :true
  validates :first_name_kana, presence: :true
  validates :postal_code, presence: :true
  validates :telephone_number, presence: :true
  validates :address, presence: :true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true


#画像のサイズを変更するメソッド
  def get_image
    if image.attached?
        image.variant(resize_to_fill: [width = 300, height = 300]).processed
    end
  end

#税込金額を算出するメソッド
  def price_in_tax
    (price * 1.1).floor  #(税抜価格✕税率).小数点以下切り捨てメソッド
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  before_create :generate_order_id
  has_many :items, through: :order_details
  has_many :order_details, dependent: :destroy
 

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :payment_method, presence: true


  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting: 0, paid_up: 1, production: 2, preparing: 3, shipped: 4 }

  after_update :update_making_status, if: :saved_change_to_status?
  
  private

  def update_making_status
    if status == "paid_up"
      order_details.where(making_status: OrderDetail.making_statuses[:cannot_start])
                   .update_all(making_status: OrderDetail.making_statuses[:waiting_for_make])
    end
  end

  def generate_order_id
    self.order_id = Time.current.strftime('%Y%m%d%H%M%S') + rand(1000..9999).to_s
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    item.price_in_tax * amount
  end

  enum making_status: {
    cannot_start: 0,    
    waiting_for_make: 1, 
    in_production: 2,    
    complete: 3          
  }

  after_update :update_order_status, if: :saved_change_to_making_status?

  private

  def update_order_status
    if in_production?
      order.update(status: :production) unless order.production?
      return
    end
    
    if order.order_details.all?(&:complete?)
      order.update(status: :preparing) unless order.preparing?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @genres = Genre.all
    @new_items = Item.order(created_at: :desc).limit(4)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="border-top text-center custom-color" style="border-color:black !important;">
  <%= image_tag "Logo_iOS.jpg", style: "width: 15%;" %>
</footer>

app/views/layouts/_header.html.erb
<header class="custom-color d-flex justify-content-between align-items-center border-bottom px-4 py-2" style="border-color:black !important;">
  <div>
    <%= link_to root_path do %>
      <%= image_tag "Logo_iOS.jpg", style: "width: 10%;" %>
    <% end %>
    <% unless controller_path.start_with?('admin/') %>
      <span class="ml-2">
        ようこそ、<%= customer_signed_in? ? current_customer.last_name : "ゲスト" %>さん!
      </span>
    <% end %>
  </div>

  <nav class="d-flex">
    <% if admin_signed_in? %>
      <%= link_to "商品一覧", admin_items_path, class: "btn btn-white mx-1" %>
      <%= link_to "会員一覧", admin_customers_path, class: "btn btn-white mx-1" %>
      <%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-white mx-1" %>
      <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-white mx-1" %>
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-white mx-1" %>

    <% elsif customer_signed_in? %>
      <%= link_to "マイページ", customers_mypage_path(current_customer), class: "btn btn-white mx-1" %>
      <%= link_to "商品一覧", items_path, class: "btn btn-white mx-1" %>
      <%= link_to "カート", cart_items_path, class: "btn btn-white mx-1" %>
      <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-white mx-1" %>

    <% else %>
      <%= link_to "About", about_path, class: "btn btn-white mx-1" %>
      <%= link_to "商品一覧", items_path, class: "btn btn-white mx-1" %>
      <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-white mx-1" %>
      <%= link_to "ログイン", new_customer_session_path, class: "btn btn-white mx-1" %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/73b476b9ae.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "d-flex flex-column min-vh-100">
    <%= render "layouts/header" %>

    <main class ="flex-grow-1">
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>